### ISSUE TITLE
Missing <utf.h>

### ISSUE THREAD

**Issue by ghost** [younix/lchat#1]
I tried to install this great project, but it seems that my system does not have the `utf.h` header.  Which one is it?  Suckless' [`libutf`](http://git.suckless.org/libutf/commit/), plan9's [`libutf`](https://github.com/cls/libutf/tree/master/include)?

**Comment by younix** [comment]
yes.  you need libutf.  as far as i know, it does not matter which one you use.

**Comment by ghost** [comment]
Thank you for your answer.  It may just have been me not configuring my system correctly.  I should get it right...
