### ISSUE TITLE
Use of BSD-specific function "strlcat"?

### ISSUE THREAD

**Issue by ghost** [younix/lchat#2]
I managed to get my local libutf working.  But I now got this error message:

```
cc -o lchat lchat.o slackline.o -L /home/josuah/.local/lib/ -lutf
lchat.o: In function `main':
/home/josuah/lchat/lchat.c:264: undefined reference to `strlcat'
collect2: error: ld returned 1 exit status
make: *** [Makefile:21: lchat] Error 1
```

At first glance, I would say that the function [strlcat](http://man.openbsd.org/?query=strlcat&apropos=0&sec=0&arch=default&manpath=OpenBSD-current#HISTORY) is not on linux, but I may be wrong.

**Comment by younix** [comment]
You are right. For non-bsd systems I have to add -lbsd to the Makefile.
